[package]
name = "rid3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.22.1"
tui = { version = "0.16", default-features = false, features = ["crossterm"] }
anyhow = "1.0.52"
id3 = "1.0.1"
tokio = { version = "1.15.0", features = ["rt-multi-thread", "macros"] }
